### ISSUE TITLE
Entity Array Index Issue

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#118]
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 128
    at com.jpii.navalbattle.pavo.grid.EntityManager.isTileFilledWithWater(EntityManager.java:169)
    at com.jpii.navalbattle.pavo.gui.GridWindow.render(GridWindow.java:72)
    at com.jpii.navalbattle.game.NavalGame.mouseMove(NavalGame.java:176)
    at com.jpii.navalbattle.game.GameComponent$2.mouseMoved(GameComponent.java:86)
    at java.awt.Component.processMouseMotionEvent(Unknown Source)
    at javax.swing.JComponent.processMouseMotionEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$200(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by maximusvladimir** [comment]
This should have been taken care of in Entity.validate(); (it's static).

**Comment by abauer** [comment]
so is this fixed / when will it be fixed

**Comment by maximusvladimir** [comment]
Not yet.

**Comment by maximusvladimir** [comment]
So umm I don't think this issue is valid anymore. Invalidating and closing.

**Comment by abauer** [comment]
it is valid, were still getting the error

**Comment by maximusvladimir** [comment]
Wait wat.

**Comment by ThomasGaubert** [comment]
This is two days overdue. This needs to be fixed ASAP.

For everyday we are behind, it's less time to work on future milestones. Due dates won't change.

**Comment by maximusvladimir** [comment]
This is not valid anymore.
