### ISSUE TITLE
NPE on launch

### ISSUE THREAD

**Issue by ThomasGaubert** [JPII/NavalBattle#174]
`Exception in thread "main" java.lang.NullPointerException
    at com.jpii.navalbattle.gui.MainMenuWindow.<init>(MainMenuWindow.java:64)
    at com.jpii.navalbattle.data.WindowHandler.initArray(WindowHandler.java:49)
    at com.jpii.navalbattle.data.WindowHandler.<init>(WindowHandler.java:38)
    at com.jpii.navalbattle.NavalBattle.main(NavalBattle.java:75)`

@abauer

**Comment by abauer** [comment]
at me?
this is not my fault i haven't changed anything...

**Comment by abauer** [comment]
how often does this occur?

**Comment by maximusvladimir** [comment]
:loudspeaker: ANTHONY BROKE IT!  ;)

**Comment by ThomasGaubert** [comment]
The error occurs on every run for me.

**Comment by ThomasGaubert** [comment]
Whoops, I deleted a line of code by accident and borked it all.

Non-issue!

**Comment by abauer** [comment]
thanks for all the worry, would like to implement gamekit windows though
