### ISSUE TITLE
Memory Issues

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#178]
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
    at java.awt.image.DataBufferInt.<init>(Unknown Source)
    at java.awt.image.Raster.createPackedRaster(Unknown Source)
    at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
    at java.awt.image.BufferedImage.<init>(Unknown Source)
    at com.jpii.navalbattle.pavo.io.PavoImage.<init>(PavoImage.java:27)
    at com.jpii.navalbattle.pavo.gui.WindowManager.render(WindowManager.java:121)
    at com.jpii.navalbattle.pavo.Game.render(Game.java:347)
    at com.jpii.navalbattle.game.NavalGame.render(NavalGame.java:252)
    at com.jpii.navalbattle.game.GameComponent.update(GameComponent.java:110)
    at com.jpii.navalbattle.game.GameComponent$3.actionPerformed(GameComponent.java:94)
    at javax.swing.Timer.fireActionPerformed(Unknown Source)
    at javax.swing.Timer$DoPostEvent.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$200(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by maximusvladimir** [comment]
That's not my fault. I said there was a memory problem.

**Comment by maximusvladimir** [comment]
Since this is an ongoing issue, it shall be closed for now.
