### ISSUE TITLE
LoginInWindow / RoketGamer

### ISSUE THREAD

**Issue by abauer** [JPII/NavalBattle#185]
Sometimes null pointer when Login Window accesses a non initiated RoketGamer.

**Comment by ThomasGaubert** [comment]
`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at com.jpii.navalbattle.gui.LoggingInWindow$1.actionPerformed(LoggingInWindow.java:72)
    at javax.swing.Timer.fireActionPerformed(Timer.java:271)
    at javax.swing.Timer$DoPostEvent.run(Timer.java:201)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:597)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)`

This is something I did, I'll fix it sometime when we get a chance. (stupid real life work)

**Comment by ThomasGaubert** [comment]
Workaround is to login using your RoketGamer account...

**Comment by ThomasGaubert** [comment]
attn: @abauer @DarkWarHero @Matthis5point0 @maximusvladimir @smeagle42
