### ISSUE TITLE
Very very rare Nimbus error.

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#79]
I don't think this is much of a problem, but very very rarely, I will get the following error:

Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.awt.Color
    at com.sun.java.swing.plaf.nimbus.NimbusStyle.getColorForState(Unknown Source)
    at javax.swing.plaf.synth.SynthStyle.getColor(Unknown Source)
    at javax.swing.plaf.synth.SynthLookAndFeel.paintRegion(Unknown Source)
    at javax.swing.plaf.synth.SynthLookAndFeel.update(Unknown Source)
    at javax.swing.plaf.synth.SynthPanelUI.update(Unknown Source)
    at javax.swing.JComponent.paintComponent(Unknown Source)
    at javax.swing.JComponent.paint(Unknown Source)
    at javax.swing.JComponent.paintToOffscreen(Unknown Source)
    at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
    at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
    at javax.swing.RepaintManager.paint(Unknown Source)
    at javax.swing.JComponent._paintImmediately(Unknown Source)
    at javax.swing.JComponent.paintImmediately(Unknown Source)
    at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
    at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
    at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
    at javax.swing.RepaintManager.access$700(Unknown Source)
    at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$1.run(Unknown Source)
    at java.awt.EventQueue$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by maximusvladimir** [comment]
This isn't too rare now. I have gotten it a total of 5 times now.

**Comment by abauer** [comment]
ive never gotten it

**Comment by ThomasGaubert** [comment]
I don't believe I've gotten it either.

**Comment by maximusvladimir** [comment]
Fine, you don't believe me? I will snapshot next time I get it.

**Comment by maximusvladimir** [comment]
Oh boy:
http://netbeans.org/bugzilla/show_bug.cgi?id=199592

**Comment by ThomasGaubert** [comment]
So not possible to fix? What happens when the error occurs?

**Comment by maximusvladimir** [comment]
It get fairly laggy and it throws an error. The program is allowed to continue to run though.

**Comment by ThomasGaubert** [comment]
Well if it's not possible to fix it, we can always listen for it and alert the user that it happened (and prompt for a restart of the program)?

**Comment by maximusvladimir** [comment]
May be we should just

**Comment by maximusvladimir** [comment]
Ok. 95% sure I fixed it as of commit id fa7c2a95e6983bce95403d1c6c379345dc409d5e. (The Nimbug fix). (Lol, play on words).

**Comment by maximusvladimir** [comment]
![image](https://f.cloud.github.com/assets/1757519/59101/fbe9fcbc-5b9e-11e2-98e8-cb4d2cf2dabd.png)

**Comment by maximusvladimir** [comment]
I had it again today. This time it wouldn't let me continue the program (meaning it crashed).

**Comment by ThomasGaubert** [comment]
Does this still happen?

**Comment by abauer** [comment]
asks also....

**Comment by maximusvladimir** [comment]
I get it occasionally.

**Comment by abauer** [comment]
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: javax.swing.plaf.nimbus.DerivedColor$UIResource cannot be cast to javax.swing.Painter
    at javax.swing.plaf.nimbus.NimbusStyle.getBackgroundPainter(Unknown Source)
    at javax.swing.plaf.nimbus.SynthPainterImpl.paintBackground(Unknown Source)
    at javax.swing.plaf.nimbus.SynthPainterImpl.paintTextPaneBackground(Unknown Source)
    at javax.swing.plaf.synth.SynthTextPaneUI.paintBackground(Unknown Source)
    at javax.swing.plaf.synth.SynthEditorPaneUI.update(Unknown Source)
    at javax.swing.JComponent.paintComponent(Unknown Source)
    at javax.swing.JComponent.paint(Unknown Source)
    at javax.swing.JComponent.paintToOffscreen(Unknown Source)
    at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
    at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
    at javax.swing.RepaintManager.paint(Unknown Source)
    at javax.swing.JComponent._paintImmediately(Unknown Source)
    at javax.swing.JComponent.paintImmediately(Unknown Source)
    at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
    at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
    at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
    at javax.swing.RepaintManager.access$700(Unknown Source)
    at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$200(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by maximusvladimir** [comment]
This isn't my fault.

**Comment by abauer** [comment]
ok...

**Comment by ThomasGaubert** [comment]
Is this fixable or should we just prompt the user to restart the game?

**Comment by maximusvladimir** [comment]
"It get fairly laggy and it throws an error. The program is allowed to continue to run though."

I think that when we get to production level, we should just do what most developers do, and place the entire program in a giant try...catch field, then report the internal exception to the user through a message box. I would expect an error like this to not be fatal, and it only lags out for a few seconds, and after that the game is fine, so we should be good.

I think this issue has to do with multi-threading.

**Comment by abauer** [comment]
ok i got a nimbus but today that actually halted the game. because it killed the log in window and i could not proceed

**Comment by maximusvladimir** [comment]
I am pretty sure this is a multithreading issue.

**Comment by abauer** [comment]
everything seems to be now-a-days

**Comment by ThomasGaubert** [comment]
This is an ongoing issue and we have measures in place to handle it. Closed.
